### PR TITLE
Adding iOS Support to Mistral.rs

### PR DESCRIPTION
**Pull request by OptimusLime**
Due to crashes during either new_metal device calls or resource allocation (see [issue on Candle main](https://github.com/huggingface/candle/issues/2322))

1. Replaced references to MTLResourceOptions::StorageMode* enums to METAL_SHARED_BUFFER_STORAGE_MODE
2. added libMetalFlashAttention.ios.metalib from [release lib](https://github.com/philipturner/metal-flash-attention/releases) of metal flash attention
3. returned LayerNorm bias to Option<Tensor> as memory overflow on 1B llama 3 was happening in iOS due to LayerNorm

Tested working on iOS 18.2 iphone14 pro and iphone 16 pro.

### CODE REVIEW

**Comment by mush4camb** [comment]
@OptimusLime do you have an idea of to work around the linker error caused by `accelerate`?

```
      candle_core::accelerate::vs_tanh::h8e1e306964523a9e in libapp.a[1655](candle_core-2d964d32b1641e21.candle_core.6aae54a28a2a4868-cgu.09.rcgu.o)
      candle_core::accelerate::vs_tanh_inplace::h40321d32addf08f9 in libapp.a[1655](candle_core-2d964d32b1641e21.candle_core.6aae54a28a2a4868-cgu.09.rcgu.o)
ld: symbol(s) not found for architecture arm64
clang++: error: linker command failed with exit code 1 (use -v to see invocation)
```

**Comment by mush4camb** [comment]
I confirm it is working.

**Review by EricLBuehler — APPROVED** [review]
Thank you!
